include(cmake/Variables.cmake)

file(GLOB ROOT_SOURCE ${SRC_DIR}/*.cpp)
file(GLOB ROOT_HEADER ${HDR_DIR}/*.h)
file(GLOB ROOT_INLINE ${HDR_DIR}/*.hpp)

file(GLOB CORE_SOURCE ${CORE_SRC_DIR}/*.cpp)
file(GLOB CORE_HEADER ${CORE_HDR_DIR}/*.h)
file(GLOB CORE_INLINE ${CORE_HDR_DIR}/*.hpp)

file(GLOB CONTROLLER_SOURCE ${CONTROLLER_SRC_DIR}/*.cpp)
file(GLOB CONTROLLER_HEADER ${CONTROLLER_HDR_DIR}/*.h)
file(GLOB CONTROLLER_INLINE ${CONTROLLER_HDR_DIR}/*.hpp)

file(GLOB MODEL_SOURCE ${MODEL_SRC_DIR}/*.cpp)
file(GLOB MODEL_HEADER ${MODEL_HDR_DIR}/*.h)
file(GLOB MODEL_INLINE ${MODEL_HDR_DIR}/*.hpp)

file(GLOB VIEW_SOURCE ${VIEW_SRC_DIR}/*.cpp)
file(GLOB VIEW_HEADER ${VIEW_HDR_DIR}/*.h)
file(GLOB VIEW_INLINE ${VIEW_HDR_DIR}/*.hpp)

file(GLOB WINDOWS_SOURCE ${WINDOWS_SRC_DIR}/*.cpp)
file(GLOB WINDOWS_HEADER ${WINDOWS_HDR_DIR}/*.h)
file(GLOB WINDOWS_INLINE ${WINDOWS_HDR_DIR}/*.hpp)

set(NOOBSTERS_LINUX_APPLICATION_HEADERS
        ${ROOT_HEADER}
        ${ROOT_INLINE}
        ${CORE_HEADER}
        ${CORE_INLINE}
        ${CONTROLLER_HEADER}
        ${CONTROLLER_INLINE}
        ${MODEL_HEADER}
        ${MODEL_INLINE}
        ${VIEW_HEADER}
        ${VIEW_INLINE}
        ${WINDOWS_HEADER}
        ${WINDOWS_INLINE}
)

set(NOOBSTERS_LINUX_APPLICATION_SOURCES
        ${ROOT_SOURCE}
        ${CORE_SOURCE}
        ${CONTROLLER_SOURCE}
        ${MODEL_SOURCE}
        ${VIEW_SOURCE}
        ${WINDOWS_SOURCE}
)
