include(cmake/Variables.cmake)

file(GLOB ROOT_SOURCE ${SRC_DIR}/*.cpp)
file(GLOB ROOT_HEADER ${HDR_DIR}/*.h)
file(GLOB ROOT_INLINE ${HDR_DIR}/*.hpp)

file(GLOB CORE_SOURCE ${CORE_SRC_DIR}/*.cpp)
file(GLOB CORE_HEADER ${CORE_HDR_DIR}/*.h)
file(GLOB CORE_INLINE ${CORE_HDR_DIR}/*.hpp)

file(GLOB CONTROLLERS_SOURCE ${CONTROLLERS_SRC_DIR}/*.cpp)
file(GLOB CONTROLLERS_HEADER ${CONTROLLERS_HDR_DIR}/*.h)
file(GLOB CONTROLLERS_INLINE ${CONTROLLERS_HDR_DIR}/*.hpp)

file(GLOB VIEWS_SOURCE ${VIEWS_SRC_DIR}/*.cpp)
file(GLOB VIEWS_HEADER ${VIEWS_HDR_DIR}/*.h)
file(GLOB VIEWS_INLINE ${VIEWS_HDR_DIR}/*.hpp)

file(GLOB WINDOWS_SOURCE ${WINDOWS_SRC_DIR}/*.cpp)
file(GLOB WINDOWS_HEADER ${WINDOWS_HDR_DIR}/*.h)
file(GLOB WINDOWS_INLINE ${WINDOWS_HDR_DIR}/*.hpp)

set(NOOBSTERS_LINUX_APPLICATION_HEADERS
        ${ROOT_HEADER}
        ${ROOT_INLINE}
        ${CORE_HEADER}
        ${CORE_INLINE}
        ${CONTROLLERS_HEADER}
        ${CONTROLLERS_INLINE}
        ${VIEWS_HEADER}
        ${VIEWS_INLINE}
        ${WINDOWS_HEADER}
        ${WINDOWS_INLINE}
)

set(NOOBSTERS_LINUX_APPLICATION_SOURCES
        ${ROOT_SOURCE}
        ${CORE_SOURCE}
        ${CONTROLLERS_SOURCE}
        ${VIEWS_SOURCE}
        ${WINDOWS_SOURCE}
)
